# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19f55745fb4ee285a6dec2ed04f9f935f9f5bbf3b8e94a6f930e30913985f081c483cb7e7f3e789dd8df9cef1705ad662fe6731d9cde5f827611a341ed050f84

test:
  secret_key_base: 82af7d25ceed64a8b8757d9e55281aea06efcf99858c1090b61369033c7afcdb3951a2ca83ce6ff708392379a7d440a45ba9f4147f3f9e9ebab5497c3c6e8d75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
